# cd.yaml 
name: Pipeline-CI 
on: 
  push: 
    branches: [ main ] 
jobs: 
  ci: 
    runs-on: ubuntu-latest 
    steps: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
    - uses: actions/checkout@v2 
    # https://github.com/shivammathur/setup-php (community) 
    - name: Setup PHP, extensions and composer with shivammathur/setup-php 
      uses: shivammathur/setup-php@v2 
      with: 
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
    - name: Cachemultiple paths
      user: actions/cache@v3.3.2
      with:
        path:
          vendor
        key ${{ runner.os }}-${{ hashfiles('composer.lock') }}

      - name "composer install"
        run: composer install --no-interaction --no-progress
    - name: LS 
      run: ls
